import fs from 'fs';
import path from 'path';
import { chromium } from 'playwright';

const [payloadPath, outputPath] = process.argv.slice(2);
if (!payloadPath || !outputPath) {
  console.error('Usage: node render_chart.mjs <payload.json> <output.png>');
  process.exit(2);
}

const payload = JSON.parse(fs.readFileSync(payloadPath, 'utf-8'));
const chartLibPath = path.resolve(process.cwd(), 'node_modules/lightweight-charts/dist/lightweight-charts.standalone.production.js');

const html = `<!doctype html>
<html>
<head>
<meta charset="utf-8" />
<style>
  html, body { margin:0; background:#0b1220; font-family: Inter, Arial, sans-serif; }
  #wrap { width: 1800px; height: 1000px; position: relative; }
  #chart { width: 1800px; height: 1000px; }
  #title { position:absolute; left:20px; top:14px; color:#e5e7eb; font-size:22px; font-weight:700; z-index:5; }
  #subtitle { position:absolute; left:20px; top:44px; color:#94a3b8; font-size:14px; z-index:5; }
  #watermark { position:absolute; right:18px; bottom:12px; color:#64748b; font-size:12px; z-index:5; }
</style>
</head>
<body>
<div id="wrap">
  <div id="title">BTC Market Structure — Lightweight Charts</div>
  <div id="subtitle"></div>
  <div id="chart"></div>
  <div id="watermark">Generated by Hermes BTC Analyst</div>
</div>
</body>
</html>`;

(async () => {
  const browser = await chromium.launch({ headless: true });
  const page = await browser.newPage({ viewport: { width: 1800, height: 1000 }, deviceScaleFactor: 2 });
  await page.setContent(html, { waitUntil: 'domcontentloaded' });
  await page.addScriptTag({ path: chartLibPath });

  await page.evaluate((p) => {
    document.getElementById('subtitle').textContent = p.subtitle || '';
    const chart = LightweightCharts.createChart(document.getElementById('chart'), {
      width: 1800,
      height: 1000,
      layout: { background: { color: '#0b1220' }, textColor: '#cbd5e1' },
      grid: { vertLines: { color: '#1f2937' }, horzLines: { color: '#1f2937' } },
      rightPriceScale: {
        borderColor: '#334155',
        scaleMargins: { top: 0.08, bottom: 0.20 }
      },
      timeScale: {
        borderColor: '#334155',
        timeVisible: true,
        secondsVisible: false,
        barSpacing: 8,
        rightOffset: 6,
      },
      crosshair: { mode: LightweightCharts.CrosshairMode.Normal },
    });

    const candle = chart.addCandlestickSeries({
      upColor: '#22c55e', downColor: '#ef4444', borderUpColor: '#22c55e', borderDownColor: '#ef4444', wickUpColor: '#22c55e', wickDownColor: '#ef4444'
    });
    candle.setData(p.candles || []);

    const volume = chart.addHistogramSeries({
      priceFormat: { type: 'volume' },
      priceScaleId: '',
      scaleMargins: { top: 0.86, bottom: 0.02 },
      lastValueVisible: false,
      priceLineVisible: false,
    });
    volume.setData(p.volume || []);

    const sma20 = chart.addLineSeries({ color: '#ef4444', lineWidth: 2, title: 'SMA20' });
    const sma50 = chart.addLineSeries({ color: '#22c55e', lineWidth: 2, title: 'SMA50' });
    const sma100 = chart.addLineSeries({ color: '#3b82f6', lineWidth: 2, title: 'SMA100' });
    const sma200 = chart.addLineSeries({ color: '#ffffff', lineWidth: 2, title: 'SMA200' });
    sma20.setData(p.sma20 || []);
    sma50.setData(p.sma50 || []);
    sma100.setData(p.sma100 || []);
    sma200.setData(p.sma200 || []);

    for (const z of p.support || []) {
      candle.createPriceLine({
        price: z.price,
        color: '#10b981',
        lineWidth: 1,
        lineStyle: LightweightCharts.LineStyle.Dashed,
        axisLabelVisible: true,
        title: z.label,
      });
    }
    for (const z of p.resistance || []) {
      candle.createPriceLine({
        price: z.price,
        color: '#f43f5e',
        lineWidth: 1,
        lineStyle: LightweightCharts.LineStyle.Dashed,
        axisLabelVisible: true,
        title: z.label,
      });
    }

    candle.setMarkers(p.markers || []);
    chart.timeScale().fitContent();
  }, payload);

  await page.waitForTimeout(600);
  await page.screenshot({ path: outputPath, type: 'png' });
  await browser.close();
})();
