from btc_analyst.reports.daily import render_markdown


def test_report_renders_crowd_positioning_section():
    data = {
        "report_date": "2026-01-01",
        "generated_at_utc": "2026-01-01 00:00:00",
        "price": 80000,
        "change_24h_pct": 0,
        "weekly_trend": "Up",
        "daily_trend": "Up",
        "trend_4h": "Up",
        "atr_daily": 1000,
        "atr_daily_pct": 1.0,
        "vol_regime": "normal",
        "volume_ratio": 1.0,
        "funding_rate": 0,
        "funding_label": "neutral",
        "oi_change_pct": 0,
        "liq_long_usd": 0,
        "liq_short_usd": 0,
        "bybit_funding_8h": 0.0001,
        "bybit_oi_delta": 1.0,
        "bybit_ls": 1.1,
        "okx_ls": 1.2,
        "cg_funding": 0.0001,
        "cg_ls": 1.0,
        "fng_value": 55,
        "fng_label": "Neutral",
        "btc_dom": 54.0,
        "aggregate_label": "neutral",
        "extreme_flag": False,
        "sources_used_count": 4,
        "missing_sources": True,
        "missing_sources_list": "coinglass",
        "funding_label_1b": "neutral",
        "oi_label": "rising",
        "bybit_ls_label": "balanced",
        "okx_ls_label": "balanced",
        "cg_funding_label": "neutral",
        "cg_ls_label": "balanced",
        "btc_dom_label": "risk-on tilt",
        "bias": "Bullish",
        "bias_rationale": "x",
        "uncertainty_reasons": "",
        "support_zones": [],
        "resistance_zones": [],
        "no_trade_description": "x",
        "position_in_range_description": "x",
        "active_setups": [],
        "active_alerts": [],
        "weekly_rhythm_note": "x",
        "is_weekend": False,
        "weekday": "Monday",
        "approaching_cme_close": False,
        "hours_to_cme_close": 0,
        "cme_gap_present": False,
        "action_now": "x",
        "wait_for": "x",
        "avoid": "x",
        "no_strong_setups": True,
        "setups_30d": 0,
        "win_rate_30d": 0,
        "avg_r_30d": 0,
        "best_day_30d": "n/a",
        "worst_day_30d": "n/a",
        "strong_hit_rate": 0,
        "false_signals_30d": 0,
        "drawdown_warning": False,
        "losing_streak": 0,
        "charts": [],
        "report_id": 1,
        "bot_version": "1.0.0",
        "next_report_at": "12:00 UTC",
    }
    md = render_markdown(data)
    assert "## 1b. Crowd Positioning" in md
    assert "Aggregate reading: neutral" in md
